import PyQt5
from . import comment #contains the UI code for the Comment, which is needed by this object which also contains the mechanics. The UI is generated by the pyuic5 tool which means it is easily updated without losing anything else if we need to change it
import sip

class Comment(PyQt5.QtWidgets.QWidget):
	"""Comment object which is made up of both the UI and the mechanics for the comment"""
	deleted = PyQt5.QtCore.pyqtSignal()
	def __init__(self,commentText,parentLayout,matchedCode):
		"""Create the comment object by loading the UI and filling it with data, and then show it on screen and add it to the parent layout in which it should sit"""

		super().__init__() #Create a widget which we can put the comment in
		self.ui = comment.Ui_Form() #Load the template UI which is a vertically layed out textedit and button together
		self.ui.setupUi(self) #Set up the UI - create the objects and put the text on the dismiss button for example
		
		#For brevity, when creating comments, we can add <code> tags. These turn into monospace black text on a grey background when displayed as we replace them here with the required styling.
		commentText = commentText.replace("<code>","<br><span style='background-color:#c7c7c7;font-family: Consolas,Monospace;'>") 
		commentText = commentText.replace("</code>","</span><br>")
		
		self.ui.commentText.setHtml(commentText) #Put the text on screen in the right place
		
		parentLayout.addWidget(self) #Insert into parent at the top so it displays on screen in the correct place
	
		self.matchedCode = matchedCode #store the match for later so that if the user dismisses the comment we don't keep making it come back
		
		self.ui.dismissButton.comment = self
	def die(self):
		"""Called when the user clicks the Dismiss Suggestion button"""
		self.deleted.emit()
		sip.delete(self) #Remove it from memory and call the destructor (which we don't have access to as it's C++)	 https://stackoverflow.com/questions/30241684/pyqt4-setparent-vs-deletelater/30245816#30245816	
		
#Create a new Comment: Comment("Consider replacing <code>OldAndBad</code> with <code>NewAndGood</code> for an improvement in efficacy",self.commentsPane)
		
